// generated by "sampctl package init"
#include <a_samp>
#include <typing-textdraw>

main() 
{
	// write code here and run "sampctl package build" to compile
	// then run "sampctl package run" to run it
}
